
[workspace]
members = ["dotfiles/dofile-rs"]

[workspace.dependencies]

[workspace.package]
version = "1.0.0"
authors = ["Nate Jensvold <jensvoldnate@gmail.com>"]
description = "A collection of resources used for setting up a new development environment"
readme = "README.md"
edition = "2021"
# build = "src/build.rs"
