#!/usr/bin/env bash

if [[ -z $TMUX ]]; then
	echo "Error: Tmux session required to use tmux-switch-dir"
	exit 0
elif [[ $# -ne 1 ]]; then
	echo 'Error - Usage: tmux-switch-dir [suffix-name]'
	exit 0
fi

suffix_name=$1
tmux_name=$(tmux display-message -p '#S')
echo "current tmux-name: $tmux_name"
# current tmux session has suffix, remove suffix for new session name
if [[ $tmux_name == *-$suffix_name ]]; then
	tmux_name=${tmux_name%"-$suffix_name"}
else
	# current tmux session does not have suffix, add for new session name
	tmux_name="${tmux_name}-${suffix_name}"
fi

echo "new tmux-name: $tmux_name"

tmux_dir=$(tmux display-message -p '#{pane_current_path}')

# create new session in background if a session of $tmux_name does not exist yet
if ! tmux has-session -t="$tmux_name" 2>/dev/null; then
	tmux new-session -ds "$tmux_name" -c "$tmux_dir"
fi

# In tmux, switch to other session
tmux switch-client -t "$tmux_name"
