#!/usr/bin/env bash

if [[ $# -eq 0 ]]; then
	path_array=($(echo "$TMUX_SESSIONIZER_PATHS" | tr ':' '\n'))

	real_paths=()
	for i in "${!path_array[@]}"; do
		tmp_path="${path_array[i]/#\~/$HOME}"

		if [[ "${tmp_path: -1}" != "/" ]]; then
			tmp_path="${tmp_path}/"
		fi
		_out=$(realpath -e -q "${tmp_path}")
		code=$?

		if [[ $code -eq 0 ]]; then
			real_paths+=("${tmp_path}")
		fi
	done

    selected=$(fd . "${real_paths[@]}" -H --min-depth=1 --max-depth=1 --type=directory | fzf)
else
	selected=$1
fi

if [[ -z $selected ]]; then
	exit 0
fi

selected_name=$(basename "$selected" | tr . _)

tmux_running=$(pgrep tmux)

# create TMUX session if its not running
if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
	tmux new-session -s "$selected_name" -c "$selected"
	exit 0
fi

# create new daemonized tmux session if tmux is running
if ! tmux has-session -t="$selected_name" 2>/dev/null; then
	tmux new-session -ds "$selected_name" -c "$selected"
fi

if [[ -z $TMUX ]]; then
	# Not in tmux, attach to session
	tmux attach -t "$selected_name"
else
	# In tmux, switch to other session
	tmux switch-client -t "$selected_name"
fi
