#!/bin/sh

# Can be ran with bash or ZSH
# Exit on errors
set -e

NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
# shellcheck disable=SC2016
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

sudo apt-get -y install build-essential
brew install gcc
