#!/bin/bash
set -e

#  Install Home manager
[ ! -e "$HOME/.config/home-manager" ] || mv "$HOME/.config/home-manager" "$HOME/.config/backup-home-manager"

# Add nix-channel for home-manager
nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
nix-channel --update

nix-shell '<home-manager>' -A install

# Ensure the ~/.config directory exists
mkdir -p ~/.config
# Link home-manager settings from environment repo
# This command msyut run after the home-manager installation so the file is not overwritten
ln -s ~/environment/settings/nix/ ~/.config/home-manager