#!/bin/bash

# Can be ran with bash or ZSH
# Exit on errors
set -e
start_dir=$(pwd)
script_path=$(realpath "$0")
script_dir=$(dirname "$script_path")
repo_root="$script_dir/../.."

# Change directory to repo root
cd "$repo_root"

git init
git remote add origin git@github.com:JateNensvold/environment.git
git fetch origin master
git reset --mixed origin/master
git branch --set-upstream-to=origin/master master

# Change back to original directory
cd "$start_dir"
