#!/bin/bash
set -e

if [ ! -e "/nix" ]
then

    # https://github.com/AlexeyRaga/home.nix/blob/10f40ab7fa7df887ebd72a02209f520dda16f9c5/install.sh
    curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install --no-confirm
else
    echo "Nix is already installed... Skipping install"
fi;

# Add Nix path to current shell
PATH="$PATH:/nix/var/nix/profiles/default/bin/nix"

/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh

nix-channel --add https://github.com/nix-community/home-manager/archive/release-23.11.tar.gz home-manager
nix-channel --update

#  Install Home manager
[ ! -e "$HOME/.config/home-manager" ] || echo "Moving existing file" && mv "$HOME/.config/home-manager" "$HOME/.config/backup-home-manager"
ln -s ~/environment/settings/nix/ ~/.config/home-manager

nix-shell '<home-manager>' -A install
