#!/bin/bash

# Can be ran with bash or ZSH
# Exit on errors
set -e

# Power level 10k Source
# https://github.com/romkatv/powerlevel10k#getting-started
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
