#!/bin/bash

# Can be ran with bash or ZSH
# Exit on errors
set -e

script_path=$(realpath "$0")
script_dir=$(dirname "$script_path")
repo_root="$script_dir/../.."

[ ! -f "$HOME/.zshrc" ] || mv "$HOME/.zshrc" "$HOME/.zshrc_backup"
# Symlink .zshrc file from environment/settings/dofile_settings
ln -s "$repo_root/settings/dotfile_settings/.zshrc" "$HOME/.zshrc"

[ ! -f "$HOME/.p10k.zsh" ] || mv "$HOME/.p10k.zsh" "$HOME/.p10k_backup.zsh"
# Symlink .p10k.zsh file from environment/settings/dofile_settings
ln -s "$repo_root/settings/dotfile_settings/.p10k.zsh" "$HOME/.p10k.zsh"

[ ! -f "$HOME/.gitconfig" ] || mv "$HOME/.gitconfig" "$HOME/.gitconfig_backup"
# Symlink .gitconfig file from environment/settings/dofile_settings
ln -s "$repo_root/settings/dotfile_settings/.gitconfig" "$HOME/.gitconfig"

[ ! -f "$HOME/.inputrc" ] || mv "$HOME/.inputrc" "$HOME/.inputrc_backup"
# Symlink .inputrc file from environment/settings/dofile_settings
ln -s "$repo_root/settings/dotfile_settings/.inputrc" "$HOME/.inputrc"

mkdir -p "$HOME/.config/cheat/cheatsheets/"

if [ -d "$HOME/.config/cheat/cheatsheets/personal" ]; then
    [ ! -d "$HOME/.config/cheat/cheatsheets/personal_backup" ] ||
        rm "$HOME/.config/cheat/cheatsheets/personal_backup"
    mv "$HOME/.config/cheat/cheatsheets/personal" "$HOME/.config/cheat/cheatsheets/personal_backup"
fi
# Symlink cheatsheets directory from environment/settings/cheats
ln -s "$repo_root/settings/cheat/cheats" "$HOME/.config/cheat/cheatsheets/personal"

[ ! -f "$HOME/.config/cheat/conf.yml" ] ||
    mv "$HOME/.config/cheat/conf.yml" \
        "$HOME/.config/cheat/conf_backup.yml"
# Symlink cheatsheets directory from environment/settings/cheats
ln -s "$repo_root/settings/cheat/conf.yml" "$HOME/.config/cheat/conf.yml"

# Clone community cheatsheet into cheat path
if [ ! -d "$HOME/.config/cheat/cheatsheets/community" ]; then
    git clone https://github.com/cheat/cheatsheets "$HOME/.config/cheat/cheatsheets/community"
fi

# Add autocompletion for cheat command
mkdir -p ~/.oh-my-zsh/custom/plugins/cheat/
wget https://raw.githubusercontent.com/cheat/cheat/master/scripts/cheat.zsh -O \
    ~/.oh-my-zsh/custom/plugins/cheat/cheat.plugin.zsh

# Link zsh functions from environment/settings/dofile_settings/zsh_scripts
if [ -e "$HOME/.zfuncs" ]; then
    mv "$HOME/.zfuncs" "$HOME/.zfuncs_backup"
fi
# Link zsh functions from environment/settings/dofile_settings/zsh_scripts
ln -s "$repo_root/settings/dotfile_settings/zsh_scripts" "$HOME/.zfuncs"
