#!/bin/zsh
# shellcheck disable=SC1071

### BREW + FZF
# uninstall multiple packages at once, async
# mnemonic [B]rew [C]lean [P]lugin (e.g. uninstall)

local uninst=$(brew leaves | eval "fzf -m --header='[brew:clean]' --query $1")

if [[ $uninst ]]; then
	for prog in $(echo $uninst); do
		brew uninstall $prog
	done
fi
