#!/bin/zsh
# shellcheck disable=SC1071

### BREW + FZF
# update multiple packages at once
# mnemonic [B]rew [U]pdate [P]lugin

local upd=$(brew leaves | eval "fzf -m --header='[brew:update]' --query $1")

if [[ $upd ]]; then
	for prog in $(echo $upd); do
		brew upgrade $prog
	done
fi
