#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
	selected=$1
else
	TMUX_SESSIONIZER_STRING=($(echo "$TMUX_SESSIONIZER_PATHS" | tr ':' '\n'))
	for i in "${!TMUX_SESSIONIZER_STRING[@]}"; do
		TMUX_SESSIONIZER_STRING[i]="${TMUX_SESSIONIZER_STRING[i]/#\~/$HOME}"
	done

	selected=$(find "${TMUX_SESSIONIZER_STRING[@]}" -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
	# exit 0
	return
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
	tmux new-session -s "$selected_name" -c "$selected"
	# exit 0
	return
fi

if ! tmux has-session -t="$selected_name" 2>/dev/null; then
	tmux new-session -ds "$selected_name" -c "$selected"
fi

tmux switch-client -t "$selected_name"
