#!/bin/bash

# Can be ran with bash or ZSH
# Exit on errors
set -e

script_root=$(dirname -- "$0")
"$script_root"/ubuntu/git-remote-sync
"$script_root"/ubuntu/nix-install
"$script_root"/ubuntu/run-home-manager

