#!/bin/sh

# Can be ran with bash or ZSH
# Exit on errors
set -e

script_root=$(dirname -- "$0")
"$script_root"/ubuntu/brew-install
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
"$script_root"/ubuntu/zsh-install
"$script_root"/ubuntu/oh-my-zsh-install
"$script_root"/ubuntu/powerlevel10k-install
"$script_root"/ubuntu/brew-tools-install
"$script_root"/ubuntu/git-remote-sync
# Setup user settings such as .zshrc, p10k etc..
"$script_root"/ubuntu/ubuntu-settings
