#!/bin/sh

# Can be ran with bash or ZSH
# Exit on errors
set -e

script_root=$(dirname -- "$0")

"$script_root"/ubuntu/brew-install
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
"$script_root"/ubuntu/zsh-install
"$script_root"/ubuntu/oh-my-zsh-install
"$script_root"/ubuntu/powerlevel10k-install
"$script_root"/ubuntu/brew-tools-install
"$script_root"/ubuntu/wsl2-docker-install.sh
"$script_root"/ubuntu/git-remote-sync
"$script_root"/ubuntu/ubuntu-settings
"$script_root"/ubuntu/cheat-settings

# brew install
# zsh install
# oh my zsh
# powerlevel 10k
# brew tools
# sync repo
# ubuntu settings

# vscode extensions
# cheat autocomplete https://github.com/cheat/cheat/tree/master/scripts
