#!/bin/sh

# Can be ran with bash or ZSH
# Exit on errors
set -e

script_root=$(dirname -- "$0")

# linux base setup script
"$script_root"/linux-setup
"$script_root"/ubuntu/vscode_extensions_install
# Install WSL2 compatible version of docker that runs without docker desktop
"$script_root"/ubuntu/wsl2-docker-install.sh
