#!/usr/bin/env zsh

### PATH
# mnemonic: [F]ind f[P]ath
# list directories in $fpath, press [enter] on an entry to list the executables inside.
# press [escape] to go back to directory listing, [escape] twice to exit completely

local loc=$(echo $fpath | sed -e $'s/ /\\\n/g' | eval "fzf ${FZF_DEFAULT_OPTS} --header='[find:fpath]'")
if [[ -d $loc ]]; then
	output=$(echo "$(rg --files $loc | rev | cut -d"/" -f1 | rev)" | eval "fzf ${FZF_DEFAULT_OPTS} --header='[find:exe] => ${loc}'")
	exit_status=$?
	if [[ $exit_status -eq 0 ]]; then
		echo "$loc/$output"
	else
		ffp
	fi
fi
