#!/usr/bin/env zsh

if [[ $1 = 'vim' && -z $TMUX ]]; then
	echo "Unable to start tmux session from vim, reopen session in tmux window..."
	return 1
fi

zle
if [[ $? -eq 0 ]]; then
	# Run tmux-sessionizer via a one-shot precmd hook to avoid zle fd issues
	# that prevent tmux from accessing /dev/tty.
	_tsession_precmd() {
		precmd_functions=(${precmd_functions:#_tsession_precmd})
		TMUX_SESSIONIZER_PATHS=$TMUX_SESSIONIZER_PATHS tmux-sessionizer
	}
	precmd_functions+=(_tsession_precmd)
	zle accept-line
else
	TMUX_SESSIONIZER_PATHS=$TMUX_SESSIONIZER_PATHS tmux-sessionizer
fi
