#!/bin/zsh
# shellcheck disable=SC1071

### UTILS
# show utils commands and custom aliases

local helptxt="fp     [find:path]
kp     [kill:process]
ks     [kill:server]
bcp    [B]rew [C]lean [P]lugin]      Uninstall brew program
bip    [B]rew [I]nstall [P]lugin]    Install brew program
bup    [B]rew [U]pdate [P]lugin]     Update brew program
scpf   [S]cp [F]older                Copy folder over ssh conection

ga     [alias]                       git add .
gc     [alias]                       git commit -m \${1}
gd     [alias]                       git diff
gdt    [alias]                       git difftool
gmt    [alias]                       git mergetool
gp     [alias]                       git push \${1} \${2}
gco    [alias]                       git checkout \${1} \${2}
gpl    [alias]                       git pull \${1} \${2}
grb    [alias]                       git rebase \${1} \${2} -i
gs     [alias]                       git status
gl     [alias]                       git ls-files \${1} | xargs wc -l

xt     [alias] view-files-recursive  eza -T
x2     [alias]                       eza --tree --level=2
x3     [alias]                       eza --tree --level=3
x4     [alias]                       eza --tree --level=4
x      [alias]                       x2

ff     [alias] find-file             var=\$(fd | fzf --header='[find:file]') && change-location \$var
sf     [alias] search-file           rg -g '!.git' --hidden
sa     [alias] search-alias          alias | fzf
se     [alias] search-env            env | fzf \${FZF_DEFAULT_OPTS} -m --header='[find:env]'
sp     [alias] search-packages       home-manager packges | fzf

nv     [alias] nix-version           nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
u      [alias]                       utils
reload [alias] reload-nix            $RELOAD_PREFIX $RELOAD_SUFFIX Current Config: \$USER=${USER} - \$NIX_HOST=${NIX_HOST} \$HARDWARE=${HARDWARE} \$ARCH=${ARCH}

c      [alias]                       \$EDITOR .
vv     [alias]                       var=\$(fd | fzf --header='[find:file]') && full_var=\$(realpath \$var) && change-location \$var && vim \$full_var
ce     [alias]                       cd ~/environment
ze     [alias]                       \$EDITOR ~/environment
zx     [alias]                       source ~/.zshrc
zz     [alias]                       \$EDITOR ~/.config/nvim
"

local cmd=$(echo $helptxt | eval "fzf ${FZF_DEFAULT_OPTS} --header='[utils:show]'" | awk '{print $1}')

if [[ -n $cmd ]]; then
	eval ${cmd}
fi
